version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gov_services_db
    environment:
      POSTGRES_DB: gov_services_db
      POSTGRES_USER: gov_user
      POSTGRES_PASSWORD: gov_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gov_services_network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: gov_services_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gov_services_network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gov_services_backend
    environment:
      - DATABASE_URL=postgresql://gov_user:gov_password@postgres:5432/gov_services_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-super-secret-key-change-in-production
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - gov_services_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  gov_services_network:
    driver: bridge
